name: Deploy LoongsonNeuq.AssignmentSubmit

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup deploy tools
      run: dotnet tool update -g vpk

    - name: Restore project
      run: dotnet restore LoongsonNeuq.AssignmentSubmit/LoongsonNeuq.AssignmentSubmit.csproj

    - name: Deploy project
      run: ./LoongsonNeuq.AssignmentSubmit/deploy.sh
    
    - name: Upload to Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AssignmentSubmit
        path: 'output'
